language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tejesh2051/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tejesh2051/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket-name: "elasticbeanstalk-us-west-2-12547896123" 
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"